### ISSUE TITLE
Authentication Single Sign On

### ISSUE THREAD

**Issue by toftof** [socialize/socialize-sdk-ios#60]
I have existing facebook/twitter authentication functionality in my app. Can i delegate this authentication to the socialize auth so that users will not have to authenticate again? Certainly i would not want users to authenticate multiple times.

**Comment by SPopenko** [comment]
@toftof you could use your existing credentials. Please take a look here for twitter example: http://socialize.github.io/socialize-sdk-ios/twitter.html#linking-to-twitter-using-existing-credentials
